### ISSUE TITLE
SliderField page crashes

### ISSUE THREAD

**Issue by GorlemZ** [buildo/bento-design-system#793] opened 2023-10-02 09:32 UTC
https://developer.bento-ds.com/Components/SliderField

**Comment by gabro** [comment] 2023-10-02 09:46
Thank you for reporting! I cannot reproduce though, can you clear the cache and retry?
If it doesn't help, which browser are you using?

I'm on Chrome and this is what I see

<img width="1792" alt="image" src="https://github.com/buildo/bento-design-system/assets/691940/45c9bf11-c787-435a-b57a-e524db41444d">

**Comment by veej** [comment] 2024-04-26 09:48
Closing since there are no updates and we cannot reproduce the issue

**Closed by veej** 2024-04-26 09:48 UTC
